### ISSUE TITLE
Additions using main branches 🚩

### ISSUE THREAD

**Issue by toastal** [purescript-graphql-client/purescript-graphql-client#2]
In your [`packages.dhall` file](https://github.com/purescript-graphql-client/purescript-graphql-client/blob/master/packages.dhall), you're referring to your additions via the `master` branch. This does not help with reproducible builds as this is a main branch and is likely to be overwritten. It's my understanding that `spago` treats these as immutable so if there are new changes on the main branch, your local machine will not get these updates without clearing your local caches, and when others use this library, the code can undergo breaking changes and fail. I was unable to add, test, and use this tool and this could be the issue, and while I haven't investigated further, this seems like a red flag. 

Please switch these `version`s to tags or commit hashes for stability.

**Comment by toastal** [comment]
I needed overrides even further down to try to use this in my `packages.dhall` that were missing from this project's file.

```dhall
{ either =
        { dependencies =
          [ "bifunctors"
          , "control"
          , "foldable-traversable"
          , "invariant"
          , "maybe"
          , "prelude"
          ]
        , repo = "ssh://git@github.com/srghma/purescript-either.git"
        , version = "patch-1"
        }
      }
, prettyprinter =
        { dependencies =
          [ "prelude"
          , "unfoldable"
          , "random"
          , "ansi"
          , "console"
          , "stringutils"
          ]
        , repo = "https://github.com/srghma/purescript-prettyprinter.git"
        , version = "4782a3b4b3b1338f490ffd98c1be20be146d951b"
        }
}
```

And now I'm getting issues with `Unknown value ArgonautCore.stringifyWithSpace`. I appreciate that you're doing updates to old libraries, but man has this become a rat's nest of version overrides that I'm not sure I feel comfortable adding to my project considering I still haven't gotten it to run.

Maybe I'm missing something, but I'll be waiting til this is a compiled out JS script to use if I can't just include `graphql-client` to my `packages.dhall` and `spago run` like the tests show 😞.

**Comment by srghma** [comment]
I'll try to reduce number of additions

**Comment by toastal** [comment]
For the record, I was able to get it to finally build (but not run) with the following base `packages.dhall`

```dhall
let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.13.8-20200831/packages.dhall sha256:cdb3529cac2cd8dd780f07c80fd907d5faceae7decfcaa11a12037df68812c83

let overrides =
      { argonaut-core =
            upstream.argonaut-core
          ⫽ { repo = "https://github.com/srghma/purescript-argonaut-core.git"
            , version = "003574c32b2addf440e461f12ed63c5e2d4dc826"
            }
      , either =
            upstream.either
          ⫽ { repo = "https://github.com/srghma/purescript-either.git"
            , version = "5aac6a0f42d00857cdf08080eed9e0a84c3ca6c5"
            }
      }

let additions =
      { graphql-client =
        { dependencies =
          [ "affjax"
          , "console"
          , "effect"
          , "generics-rep"
          , "node-fs-aff"
          , "prelude"
          , "proxy"
          , "psci-support"
          , "record"
          , "argonaut-core"
          , "argonaut-codecs"
          , "argonaut-generic"
          , "typelevel-prelude"
          , "debug"
          , "mkdirp-aff"
          , "spec"
          , "variant"
          , "ansi"
          , "optparse"
          , "protolude"
          , "ps-cst"
          , "homogeneous-records"
          , "unordered-collection"
          , "web-socket"
          ]
        , repo =
            "https://github.com/purescript-graphql-client/purescript-graphql-client.git"
        , version = "5fe4e7022833f5d091a8b3107b9e72630e0f64b2"
        }
      , homogeneous-records =
        { dependencies =
          [ "record", "prelude", "typelevel-prelude", "unfoldable", "control" ]
        , repo = "https://github.com/srghma/purescript-homogeneous-records.git"
        , version = "38e2fbc7779976d262779cc78b6dc23cb9cfb549"
        }
      , mkdirp-aff =
        { dependencies =
          [ "prelude"
          , "effect"
          , "node-fs-aff"
          , "node-fs"
          , "node-path"
          , "either"
          , "exceptions"
          , "aff"
          ]
        , repo = "https://github.com/leighman/purescript-mkdirp-aff.git"
        , version = "43c0f7a271b9435d55b08d81e2e10f1f2901dbec"
        }
      , prettyprinter =
        { dependencies = [ "prelude", "unfoldable", "console", "stringutils" ]
        , repo = "https://github.com/srghma/purescript-prettyprinter.git"
        , version = "4782a3b4b3b1338f490ffd98c1be20be146d951b"
        }
      , protolude =
        { dependencies =
          [ "prelude"
          , "effect"
          , "node-fs-aff"
          , "node-fs"
          , "node-path"
          , "either"
          , "exceptions"
          , "aff"
          ]
        , repo = "https://github.com/srghma/purescript-protolude.git"
        , version = "c56d72750c954cc9ff6ae6752204a046fe93b3f6"
        }
      , ps-cst =
        { dependencies =
          [ "console"
          , "effect"
          , "generics-rep"
          , "psci-support"
          , "record"
          , "strings"
          , "spec"
          , "node-path"
          , "node-fs-aff"
          , "ansi"
          , "prettyprinter"
          , "debug"
          ]
        , repo = "https://github.com/purescript-codegen/purescript-ps-cst.git"
        , version = "c9068f8e53daf19df0035fcafffec2c356f3157a"
        }
      , unordered-collection =
        { dependencies =
          [ "enums"
          , "functions"
          , "integers"
          , "lists"
          , "prelude"
          , "record"
          , "tuples"
          , "typelevel-prelude"
          ]
        , repo =
            "https://github.com/fehrenbach/purescript-unordered-collections.git"
        , version = "e91628369b4ea69d064dff624b2def0efbaf9354"
        }
      }

in  upstream ⫽ overrides ⫽ additions
```

**Comment by srghma** [comment]
updated, but there is a max stack size error

```
./regenerate-examples.sh && yarn run examples:test --watch
+ rm -fdR examples/swapi
+ rm -fdR examples/github
+ spago run --main GraphqlClientGenerator.Main --node-args '--input-url https://elm-graphql.herokuapp.com/ --output examples/swapi --api Examples.Swapi --custom-scalars-module Examples.SwapiCustomScalars'
[info] Installation complete.
           Src   Lib   All
Warnings   0     0     0
Errors     0     0     0
[info] Build succeeded.
+ spago run --main GraphqlClientGenerator.Main --node-args '--input-url https://api.github.com/graphql --header "Authorization: Bearer dbd4c239b0bbaa40ab0ea291fa811775da8f5b59" --output examples/github --api Examples.Github'
[info] Installation complete.
           Src   Lib   All
Warnings   0     0     0
Errors     0     0     0
[info] Build succeeded.
/home/srghma/projects/purescript-graphql-client/output/Effect.Aff/foreign.js:532
                throw util.fromLeft(step);
                ^

RangeError: Maximum call stack size exceeded
    at Nesting.value0 (/home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:777:33)
    at /home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:754:118
    at /home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:751:38
    at /home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:736:71
    at /home/srghma/projects/purescript-graphql-client/output/Data.Lazy/foreign.js:8:9
    at Object.exports.force (/home/srghma/projects/purescript-graphql-client/output/Data.Lazy/foreign.js:15:10)
    at forceSimpleDocStream (/home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:393:77)
    at forceSimpleDocStream (/home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:393:46)
    at forceSimpleDocStream (/home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:393:46)
    at forceSimpleDocStream (/home/srghma/projects/purescript-graphql-client/output/PrettyprinterRenderable/index.js:393:46)
```

maybe I will use https://github.com/natefaubion/purescript-dodo-printer for ps-cst

**Comment by srghma** [comment]
blocked by https://github.com/natefaubion/purescript-dodo-printer/issues/2

**Comment by srghma** [comment]
temporary pinned the older version of ps-cst without this error
